title: Schema.org
description: Schema.org provides schemas for structured data on the Internet
baseurl: "/schemaorg"
url: "https://nlweb-ai.github.io"
repository: "nlweb-ai/schemaorg"

# GitHub Pages settings
theme: null
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Process all files
markdown: kramdown
include:
  - "*.html"
  - "*.md"
  - "_*"

# Collections for schema types
collections:
  types:
    output: true
    permalink: /:name
  properties:
    output: true
    permalink: /:name

# Default layout
defaults:
  - scope:
      path: ""
      type: "types"
    values:
      layout: "type"
  - scope:
      path: ""
      type: "properties"
    values:
      layout: "property"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor