title: Schema.org
description: Schema.org provides schemas for structured data on the Internet
baseurl: "/schemaorg"
url: "https://nlweb-ai.github.io"

# GitHub Pages settings
theme: null
plugins: []

# Process all HTML files
markdown: kramdown
include:
  - "*.html"
  - "*.md"

# Collections for schema types
collections:
  types:
    output: true
    permalink: /:name:output_ext
  properties:
    output: true
    permalink: /:name:output_ext

# Default layout
defaults:
  - scope:
      path: ""
      type: "types"
    values:
      layout: "type"
  - scope:
      path: ""
      type: "properties"
    values:
      layout: "property"