name: Generate and Deploy Schema Pages

on:
  push:
    branches: [ main, master ]
    paths:
      - 'data/schema.ttl'
      - 'data/examples/**'
      - 'generate_schema_pages.py'
      - 'generate_jekyll_pages.py'
      - 'generate_index_page.py'
      - '.github/workflows/generate-pages-deploy.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      
      - name: Generate schema pages
        run: |
          echo "=== Running Jekyll generator ==="
          python generate_jekyll_pages.py
          echo ""
          echo "=== Checking generated files ==="
          echo "Types directory:"
          ls -la docs/_types/ 2>/dev/null | head -5 || echo "_types directory not found"
          echo ""
          echo "Properties directory:"
          ls -la docs/_properties/ 2>/dev/null | head -5 || echo "_properties directory not found"
          echo ""
          echo "=== Running index generator ==="
          python generate_index_page.py
      
      - name: List generated files
        run: |
          echo "Contents of docs directory:"
          ls -la docs/
          echo ""
          echo "Sample type files in _types:"
          ls docs/_types/ | head -5
          echo ""
          echo "Sample property files in _properties:"
          ls docs/_properties/ | head -5
          echo ""
          echo "Total type files:"
          ls docs/_types/*.md 2>/dev/null | wc -l
          echo ""
          echo "Total property files:"
          ls docs/_properties/*.md 2>/dev/null | wc -l
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ./docs
      
      - name: Build Jekyll site
        run: |
          cd docs
          echo "=== Files before Jekyll build ==="
          echo "Types in _types:"
          ls _types/*.md | head -5 || echo "No types found"
          echo "Properties in _properties:"
          ls _properties/*.md | head -5 || echo "No properties found"
          echo ""
          echo "=== Building Jekyll ==="
          bundle install
          bundle exec jekyll build --baseurl /schemaorg --verbose
          echo ""
          echo "=== Files after Jekyll build ==="
          echo "Contents of _site:"
          ls -la _site/ | head -20
          echo "Looking for Person.html in _site:"
          find _site -name "*Person*" -o -name "*person*" | head -10
        env:
          JEKYLL_ENV: production
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the Jekyll output
          path: './docs/_site'
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4